[cmake]
version = "3.15"
cmkr-include = "cmake/cmkr.cmake"
cpp-flags = ["-m32"] # this spams a bunch of warning when compiling using msvc, TODO: find a way to only do this with gcc
c-flags = ["-m32"]

[project]
name = "photon"
languages = ["C", "CXX"]
description = "Photon is a mod loader for Portal 2."

[variables]
PORTAL2_DIR = "D:/SteamLibrary/steamapps/common/Portal 2"

[target.subhook]
type    = "static"
alias   = "Zeex::subhook"
sources = ["vendor/subhook/subhook.c"]
headers = ["vendor/subhook/subhook.h"]

msvc.compile-options     = ["/MP"]
msvc.compile-definitions = ["SUBHOOK_STATIC"]

[target.lodepng]
type    = "static"
alias   = "lvandeve::lodepng"
sources = ["vendor/lodepng/lodepng.cpp"]
headers = ["vendor/lodepng/lodepng.h"]

msvc.compile-options = ["/MP"]

[target.zip]
type    = "static"
alias   = "kuba--::zip"
sources = ["vendor/zip/src/*.c"]
headers = ["vendor/zip/src/*.h"]

msvc.compile-options = ["/MP"]

[target.photon]
type                = "shared"
sources             = ["src/**.cpp", "src/**.h"]
include-directories = ["src", "vendor", "vendor/json/single_include", "vendor/zip/src"]
compile-features    = ["cxx_std_20"]
compile-definitions = ["NOMINMAX"]
link-libraries      = ["Zeex::subhook", "lvandeve::lodepng", "kuba--::zip"]

msvc.compile-options     = ["/MP", "/Zc:preprocessor"]
msvc.compile-definitions = ["SUBHOOK_STATIC"]
gcc.compile-options      = ["-fPIC", "-fpermissive"]
gcc.compile-definitions  = ["_GNU_SOURCE"]

[target.example-mod]
type                = "shared"
sources             = ["example-mod/**.cpp", "example-mod/**.h"]
include-directories = ["example-mod", "src/sdk"]
compile-features    = ["cxx_std_20"]
compile-definitions = ["NOMINMAX"]

msvc.compile-options     = ["/MP", "/Zc:preprocessor"]
gcc.compile-options      = ["-fPIC", "-fpermissive"]
gcc.compile-definitions  = ["_GNU_SOURCE"]

[[install]]
targets = ["photon"]
destination = "${PORTAL2_DIR}"

[[install]]
targets = ["example-mod"]
destination = "${PORTAL2_DIR}/photon"
