name: CD

on:
  push:
    tags: '*'

jobs:
  build-lin:
    name: Linux Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-10-multilib
      - name: Build
        env:
          RELEASE_BUILD: 1
        run: make -j$(nproc)
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: photon-linux
          path: photon.so
          if-no-files-found: error
  build-win:
    name: Windows Build
    runs-on: windows-2019
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Build
        env:
          RELEASE_BUILD: 1
        run: msbuild -m -t:photon -p:"Configuration=Release;Platform=x86" photon.sln
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: photon-windows
          path: bin\photon.dll
          if-no-files-found: error
      - name: Upload PDB Artifact
        uses: actions/upload-artifact@v3
        with:
          name: photon-windows-pdb
          path: bin\photon.pdb
          if-no-files-found: error
  release:
    name: Release
    if: github.repository == 'hero622/photon'
    needs: [build-lin, build-win]
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux Build
        uses: actions/download-artifact@v3
        with:
          name: photon-linux
      - name: Download Windows Build
        uses: actions/download-artifact@v3
        with:
          name: photon-windows
      - name: Download Windows PDB
        uses: actions/download-artifact@v3
        with:
          name: photon-windows-pdb
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ![CD](https://github.com/hero622/photon/workflows/CD/badge.svg)

            **Installation**
            - Place the binary into the game folder e.g. `Portal 2`
            - Open developer console and enter `plugin_load photon`

            ---

            **Changelog**
            TODO
          files: |
            photon.so
            photon.dll
            photon.pdb
          prerelease: ${{ contains(github.ref, '-pre') }}
          fail_on_unmatched_files: true
