name: CI

on:
  push:
    branches: '**'
    tags-ignore: '**'
    paths-ignore:
      - '.github/*'
      - '.github/workflows/CD.yml'
      - '.gitattributes'
      - '.gitignore'
      - 'docs/**'
      - '**.md'
      - 'LICENSE'
  pull_request:
  workflow_dispatch:

jobs:
  build-lin:
    if: false
    name: Linux Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-10-multilib
      - name: Build
        run: make -j$(nproc)
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: photon-linux
          path: photon.so
          if-no-files-found: error
  build-win:
    name: Windows Build
    runs-on: windows-2019
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
          submodules: true
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Build
        run: msbuild -m -t:photon -p:"Configuration=Release;Platform=x86" photon.sln
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: photon-windows
          path: |
            bin\photon.dll
            bin\photon.pdb
          if-no-files-found: error
